name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  shared_preferences: ^2.2.2

  cancellable: ^2.4.0
  anlifecycle: ^3.5.1
  an_lifecycle_cancellable: ^2.5.2
  an_viewmodel: ^3.5.1
  an_dialogs: ^1.3.0
  an_toast: ^1.1.0

  an_modules:
    path: ../

  common:
    path: modules/common

  lib_a:
    path: modules/lib_a
  lib_b:
    path: modules/lib_b

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:

  uses-material-design: true