name: common
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  cancellable: ^2.4.0
  anlifecycle: ^3.5.1
  an_lifecycle_cancellable: ^2.5.2
  an_viewmodel: ^3.5.1
  an_dialogs: ^1.3.0
  an_toast: ^1.1.0

  an_modules:
    path: ../../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any


flutter:
  uses-material-design: true
