name: common
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

  cancellable: ^2.3.0
  anlifecycle: ^3.3.0
  an_lifecycle_cancellable: ^2.4.1
  an_viewmodel: ^3.3.0

  an_modules:
    path: ../../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
