name: lib_b
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  an_modules:
    path: ../../../

  common:
    path: ../common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: BModule  # 在 Android 中启用当前模块
      ios:
        dartPluginClass: BModule  # 在 ios 中启用当前模块
      windows:
        dartPluginClass: BModule  # 在 windows 中启用当前模块
      web:
        pluginClass: BModule  # 在 web 中启用当前模块
        fileName: src/module.dart # 注意与其他的配置不一样
    # 在其他的平台中会不存在当前模块

  uses-material-design: true
